import 'dart:convert';

import 'resources.dart';
import 'runtime.dart';

// Code generated by Scalar SDK Generator. DO NOT EDIT.

class DemoApiScalarGalaxy {
  final ApiClient _client;
  late final PlanetsResource planets;
  late final CelestialBodiesResource celestialBodies;
  late final AuthenticationResource authentication;

  DemoApiScalarGalaxy({
    String? baseUrl,
    Map<String, String>? defaultHeaders,
    String? bearerToken, // DEMO_API_SCALAR_GALAXY_BEARER_TOKEN
    String? username, // DEMO_API_SCALAR_GALAXY_USERNAME
    String? password, // DEMO_API_SCALAR_GALAXY_PASSWORD
    String? apiKeyHeader, // DEMO_API_SCALAR_GALAXY_API_KEY_HEADER
    String? apiKeyQuery, // DEMO_API_SCALAR_GALAXY_API_KEY_QUERY
    String? apiKeyCookie, // DEMO_API_SCALAR_GALAXY_API_KEY_COOKIE
    String? bearerToken2, // DEMO_API_SCALAR_GALAXY_BEARER_TOKEN
    String? bearerToken3, // DEMO_API_SCALAR_GALAXY_BEARER_TOKEN
  }) : _client = ApiClient(
         baseUrl: baseUrl,
         defaultHeaders: defaultHeaders,
         authHeaders: {
           if (bearerToken != null) 'Authorization': 'Bearer $bearerToken',
           if (_basicAuth(username, password) != null)
             'Authorization': _basicAuth(username, password)!,
           if (apiKeyHeader != null) "X-API-Key": apiKeyHeader,
           if (bearerToken2 != null) 'Authorization': 'Bearer $bearerToken2',
           if (bearerToken3 != null) 'Authorization': 'Bearer $bearerToken3',
         },
         authQuery: {if (apiKeyQuery != null) "api_key": apiKeyQuery},
         authCookies: {if (apiKeyCookie != null) "api_key": apiKeyCookie},
       ) {
    planets = PlanetsResource(_client);
    celestialBodies = CelestialBodiesResource(_client);
    authentication = AuthenticationResource(_client);
  }
}

String? _basicAuth(String? username, String? password) {
  if (username == null || password == null) return null;
  return 'Basic ${base64Encode(utf8.encode('$username:$password'))}';
}
