import 'dart:convert';

// Code generated by Scalar SDK Generator. DO NOT EDIT.

class CelestialBody {
  final Map<String, Object?> additionalProperties;
  const CelestialBody({this.additionalProperties = const {}});
  factory CelestialBody.fromJson(Map<String, Object?> json) =>
      CelestialBody(additionalProperties: json);
  Map<String, Object?> toJson() => additionalProperties;
  @override
  String toString() => jsonEncode(toJson());
}

class Credentials {
  final String email;

  const Credentials({required this.email});

  factory Credentials.fromJson(Map<String, Object?> json) {
    return Credentials(email: json["email"] as String);
  }

  Map<String, Object?> toJson() {
    return {"email": email};
  }

  @override
  String toString() => jsonEncode(toJson());
}

class PaginatedResource {
  final Map<String, Object?>? meta;

  const PaginatedResource({this.meta});

  factory PaginatedResource.fromJson(Map<String, Object?> json) {
    return PaginatedResource(
      meta: json["meta"] is Map<String, Object?>
          ? json["meta"]
          : Map<String, Object?>.from(json["meta"] as Map? ?? const {}),
    );
  }

  Map<String, Object?> toJson() {
    return {if (meta != null) "meta": meta};
  }

  @override
  String toString() => jsonEncode(toJson());
}

class Planet {
  final int id;
  final String name;
  final String? description;
  final String type;
  final double? habitabilityIndex;
  final Map<String, Object?>? physicalProperties;
  final List<Map<String, Object?>>? atmosphere;
  final String? discoveredAt;
  final String? image;
  final List<Satellite>? satellites;
  final User? creator;
  final List<String>? tags;
  final String? lastUpdated;
  final String? successCallbackUrl;
  final String? failureCallbackUrl;

  const Planet({
    required this.id,
    required this.name,
    this.description,
    required this.type,
    this.habitabilityIndex,
    this.physicalProperties,
    this.atmosphere,
    this.discoveredAt,
    this.image,
    this.satellites,
    this.creator,
    this.tags,
    this.lastUpdated,
    this.successCallbackUrl,
    this.failureCallbackUrl,
  });

  factory Planet.fromJson(Map<String, Object?> json) {
    return Planet(
      id: (json["id"] as num).toInt(),
      name: json["name"] as String,
      description: json["description"] as String?,
      type: json["type"] as String?,
      habitabilityIndex: (json["habitabilityIndex"] as num?)?.toDouble(),
      physicalProperties: json["physicalProperties"] is Map<String, Object?>
          ? json["physicalProperties"]
          : Map<String, Object?>.from(
              json["physicalProperties"] as Map? ?? const {},
            ),
      atmosphere: (json["atmosphere"] as List? ?? const [])
          .map(
            (item) => item is Map<String, Object?>
                ? item
                : Map<String, Object?>.from(item as Map? ?? const {}),
          )
          .whereType<Map<String, Object?>>()
          .toList(),
      discoveredAt: json["discoveredAt"] as String?,
      image: json["image"] as String?,
      satellites: (json["satellites"] as List? ?? const [])
          .map(
            (item) => Satellite.fromJson(
              item is Map<String, Object?>
                  ? item
                  : Map<String, Object?>.from(item as Map? ?? const {}),
            ),
          )
          .whereType<Satellite>()
          .toList(),
      creator: User.fromJson(
        json["creator"] is Map<String, Object?>
            ? json["creator"]
            : Map<String, Object?>.from(json["creator"] as Map? ?? const {}),
      ),
      tags: (json["tags"] as List? ?? const [])
          .map((item) => item as String?)
          .whereType<String>()
          .toList(),
      lastUpdated: json["lastUpdated"] as String?,
      successCallbackUrl: json["successCallbackUrl"] as String?,
      failureCallbackUrl: json["failureCallbackUrl"] as String?,
    );
  }

  Map<String, Object?> toJson() {
    return {
      "id": id,
      "name": name,
      if (description != null) "description": description,
      "type": type,
      if (habitabilityIndex != null) "habitabilityIndex": habitabilityIndex,
      if (physicalProperties != null) "physicalProperties": physicalProperties,
      if (atmosphere != null)
        "atmosphere": atmosphere.map((item) => item).toList(),
      if (discoveredAt != null) "discoveredAt": discoveredAt,
      if (image != null) "image": image,
      if (satellites != null)
        "satellites": satellites.map((item) => item.toJson()).toList(),
      if (creator != null) "creator": creator.toJson(),
      if (tags != null) "tags": tags.map((item) => item).toList(),
      if (lastUpdated != null) "lastUpdated": lastUpdated,
      if (successCallbackUrl != null) "successCallbackUrl": successCallbackUrl,
      if (failureCallbackUrl != null) "failureCallbackUrl": failureCallbackUrl,
    };
  }

  @override
  String toString() => jsonEncode(toJson());
}

class Satellite {
  final int? id;
  final String name;
  final String? description;
  final double? diameter;
  final String type;
  final Map<String, Object?>? orbit;

  const Satellite({
    this.id,
    required this.name,
    this.description,
    this.diameter,
    required this.type,
    this.orbit,
  });

  factory Satellite.fromJson(Map<String, Object?> json) {
    return Satellite(
      id: (json["id"] as num?)?.toInt(),
      name: json["name"] as String,
      description: json["description"] as String?,
      diameter: (json["diameter"] as num?)?.toDouble(),
      type: json["type"] as String?,
      orbit: json["orbit"] is Map<String, Object?>
          ? json["orbit"]
          : Map<String, Object?>.from(json["orbit"] as Map? ?? const {}),
    );
  }

  Map<String, Object?> toJson() {
    return {
      if (id != null) "id": id,
      "name": name,
      if (description != null) "description": description,
      if (diameter != null) "diameter": diameter,
      "type": type,
      if (orbit != null) "orbit": orbit,
    };
  }

  @override
  String toString() => jsonEncode(toJson());
}

class Token {
  final String? token;

  const Token({this.token});

  factory Token.fromJson(Map<String, Object?> json) {
    return Token(token: json["token"] as String?);
  }

  Map<String, Object?> toJson() {
    return {if (token != null) "token": token};
  }

  @override
  String toString() => jsonEncode(toJson());
}

class User {
  final int? id;
  final String? name;

  const User({this.id, this.name});

  factory User.fromJson(Map<String, Object?> json) {
    return User(
      id: (json["id"] as num?)?.toInt(),
      name: json["name"] as String?,
    );
  }

  Map<String, Object?> toJson() {
    return {if (id != null) "id": id, if (name != null) "name": name};
  }

  @override
  String toString() => jsonEncode(toJson());
}
