import 'models.dart';
import 'runtime.dart';

// Code generated by Scalar SDK Generator. DO NOT EDIT.

class PlanetsResource {
  final ApiClient _client;
  late final PlanetsResourceRawResponses withRawResponse;

  PlanetsResource(this._client) {
    withRawResponse = PlanetsResourceRawResponses(_client);
  }

  Future<Map<String, Object?>> list({
    PlanetsListParams params = const PlanetsListParams(),
    RequestOptions? requestOptions,
  }) async {
    final response = await _client.request(
      "GET",
      "/planets",
      pathParams: const {},
      queryParams: {"limit": params.limit, "offset": params.offset},
      headers: const {},
      cookies: const {},
      requestOptions: requestOptions,
    );
    return response is Map<String, Object?>
        ? response
        : Map<String, Object?>.from(response as Map? ?? const {});
  }

  Future<Planet> create({
    PlanetsCreateParams params = const PlanetsCreateParams(),
    RequestOptions? requestOptions,
  }) async {
    final response = await _client.request(
      "POST",
      "/planets",
      pathParams: const {},
      queryParams: const {},
      headers: const {},
      cookies: const {},
      body: {
        "name": params.name,
        "description": params.description,
        "type": params.type,
        "habitabilityIndex": params.habitabilityIndex,
        "physicalProperties": params.physicalProperties,
        "atmosphere": params.atmosphere,
        "discoveredAt": params.discoveredAt,
        "image": params.image,
        "satellites": params.satellites,
        "creator": params.creator,
        "tags": params.tags,
        "successCallbackUrl": params.successCallbackUrl,
        "failureCallbackUrl": params.failureCallbackUrl,
      },
      contentType: "application/json",
      bodyEncoding: "json",
      requestOptions: requestOptions,
    );
    return Planet.fromJson(
      response is Map<String, Object?>
          ? response
          : Map<String, Object?>.from(response as Map? ?? const {}),
    );
  }

  Future<Planet> retrieve(
    PlanetsRetrieveParams params, {
    RequestOptions? requestOptions,
  }) async {
    final response = await _client.request(
      "GET",
      "/planets/{planetId}",
      pathParams: {"planetId": params.planetId},
      queryParams: const {},
      headers: const {},
      cookies: const {},
      requestOptions: requestOptions,
    );
    return Planet.fromJson(
      response is Map<String, Object?>
          ? response
          : Map<String, Object?>.from(response as Map? ?? const {}),
    );
  }

  Future<Planet> update(
    PlanetsUpdateParams params, {
    RequestOptions? requestOptions,
  }) async {
    final response = await _client.request(
      "PUT",
      "/planets/{planetId}",
      pathParams: {"planetId": params.planetId},
      queryParams: const {},
      headers: const {},
      cookies: const {},
      body: {
        "name": params.name,
        "description": params.description,
        "type": params.type,
        "habitabilityIndex": params.habitabilityIndex,
        "physicalProperties": params.physicalProperties,
        "atmosphere": params.atmosphere,
        "discoveredAt": params.discoveredAt,
        "image": params.image,
        "satellites": params.satellites,
        "creator": params.creator,
        "tags": params.tags,
        "successCallbackUrl": params.successCallbackUrl,
        "failureCallbackUrl": params.failureCallbackUrl,
      },
      contentType: "application/json",
      bodyEncoding: "json",
      requestOptions: requestOptions,
    );
    return Planet.fromJson(
      response is Map<String, Object?>
          ? response
          : Map<String, Object?>.from(response as Map? ?? const {}),
    );
  }

  Future<void> delete(
    PlanetsDeleteParams params, {
    RequestOptions? requestOptions,
  }) async {
    final response = await _client.request(
      "DELETE",
      "/planets/{planetId}",
      pathParams: {"planetId": params.planetId},
      queryParams: const {},
      headers: const {},
      cookies: const {},
      requestOptions: requestOptions,
    );
    return;
  }

  Future<Map<String, Object?>> uploadImage(
    PlanetsUploadImageParams params, {
    RequestOptions? requestOptions,
  }) async {
    final response = await _client.request(
      "POST",
      "/planets/{planetId}/image",
      pathParams: {"planetId": params.planetId},
      queryParams: const {},
      headers: const {},
      cookies: const {},
      body: {"image": params.image},
      contentType: "multipart/form-data",
      bodyEncoding: "multipart",
      requestOptions: requestOptions,
    );
    return response is Map<String, Object?>
        ? response
        : Map<String, Object?>.from(response as Map? ?? const {});
  }
}

class PlanetsListParams {
  final int? limit;
  final int? offset;

  const PlanetsListParams({this.limit, this.offset});

  Map<String, Object?> toJson() => {
    if (limit != null) "limit": limit,
    if (offset != null) "offset": offset,
  };
}

class PlanetsCreateParams {
  final String? name;
  final String? description;
  final String? type;
  final double? habitabilityIndex;
  final Map<String, Object?>? physicalProperties;
  final List<Map<String, Object?>>? atmosphere;
  final String? discoveredAt;
  final String? image;
  final List<Satellite>? satellites;
  final User? creator;
  final List<String>? tags;
  final String? successCallbackUrl;
  final String? failureCallbackUrl;

  const PlanetsCreateParams({
    this.name,
    this.description,
    this.type,
    this.habitabilityIndex,
    this.physicalProperties,
    this.atmosphere,
    this.discoveredAt,
    this.image,
    this.satellites,
    this.creator,
    this.tags,
    this.successCallbackUrl,
    this.failureCallbackUrl,
  });

  Map<String, Object?> toJson() => {
    if (name != null) "name": name,
    if (description != null) "description": description,
    if (type != null) "type": type,
    if (habitabilityIndex != null) "habitabilityIndex": habitabilityIndex,
    if (physicalProperties != null) "physicalProperties": physicalProperties,
    if (atmosphere != null) "atmosphere": atmosphere,
    if (discoveredAt != null) "discoveredAt": discoveredAt,
    if (image != null) "image": image,
    if (satellites != null) "satellites": satellites,
    if (creator != null) "creator": creator,
    if (tags != null) "tags": tags,
    if (successCallbackUrl != null) "successCallbackUrl": successCallbackUrl,
    if (failureCallbackUrl != null) "failureCallbackUrl": failureCallbackUrl,
  };
}

class PlanetsRetrieveParams {
  final int planetId;

  const PlanetsRetrieveParams({required this.planetId});

  Map<String, Object?> toJson() => {if (planetId != null) "planetId": planetId};
}

class PlanetsUpdateParams {
  final int planetId;
  final String? name;
  final String? description;
  final String? type;
  final double? habitabilityIndex;
  final Map<String, Object?>? physicalProperties;
  final List<Map<String, Object?>>? atmosphere;
  final String? discoveredAt;
  final String? image;
  final List<Satellite>? satellites;
  final User? creator;
  final List<String>? tags;
  final String? successCallbackUrl;
  final String? failureCallbackUrl;

  const PlanetsUpdateParams({
    required this.planetId,
    this.name,
    this.description,
    this.type,
    this.habitabilityIndex,
    this.physicalProperties,
    this.atmosphere,
    this.discoveredAt,
    this.image,
    this.satellites,
    this.creator,
    this.tags,
    this.successCallbackUrl,
    this.failureCallbackUrl,
  });

  Map<String, Object?> toJson() => {
    if (planetId != null) "planetId": planetId,
    if (name != null) "name": name,
    if (description != null) "description": description,
    if (type != null) "type": type,
    if (habitabilityIndex != null) "habitabilityIndex": habitabilityIndex,
    if (physicalProperties != null) "physicalProperties": physicalProperties,
    if (atmosphere != null) "atmosphere": atmosphere,
    if (discoveredAt != null) "discoveredAt": discoveredAt,
    if (image != null) "image": image,
    if (satellites != null) "satellites": satellites,
    if (creator != null) "creator": creator,
    if (tags != null) "tags": tags,
    if (successCallbackUrl != null) "successCallbackUrl": successCallbackUrl,
    if (failureCallbackUrl != null) "failureCallbackUrl": failureCallbackUrl,
  };
}

class PlanetsDeleteParams {
  final int planetId;

  const PlanetsDeleteParams({required this.planetId});

  Map<String, Object?> toJson() => {if (planetId != null) "planetId": planetId};
}

class PlanetsUploadImageParams {
  final int planetId;
  final String? image;

  const PlanetsUploadImageParams({required this.planetId, this.image});

  Map<String, Object?> toJson() => {
    if (planetId != null) "planetId": planetId,
    if (image != null) "image": image,
  };
}

class PlanetsResourceRawResponses {
  final ApiClient _client;
  const PlanetsResourceRawResponses(this._client);

  Future<RawResponse<Map<String, Object?>>> list({
    PlanetsListParams params = const PlanetsListParams(),
    RequestOptions? requestOptions,
  }) async {
    final response = await _client.requestRaw(
      "GET",
      "/planets",
      pathParams: const {},
      queryParams: {"limit": params.limit, "offset": params.offset},
      headers: const {},
      cookies: const {},
      requestOptions: requestOptions,
    );
    final parsed = response.body is Map<String, Object?>
        ? response.body
        : Map<String, Object?>.from(response.body as Map? ?? const {});
    return RawResponse(
      statusCode: response.statusCode,
      headers: response.headers,
      rawBody: response.rawBody,
      body: parsed,
    );
  }

  Future<RawResponse<Planet>> create({
    PlanetsCreateParams params = const PlanetsCreateParams(),
    RequestOptions? requestOptions,
  }) async {
    final response = await _client.requestRaw(
      "POST",
      "/planets",
      pathParams: const {},
      queryParams: const {},
      headers: const {},
      cookies: const {},
      body: {
        "name": params.name,
        "description": params.description,
        "type": params.type,
        "habitabilityIndex": params.habitabilityIndex,
        "physicalProperties": params.physicalProperties,
        "atmosphere": params.atmosphere,
        "discoveredAt": params.discoveredAt,
        "image": params.image,
        "satellites": params.satellites,
        "creator": params.creator,
        "tags": params.tags,
        "successCallbackUrl": params.successCallbackUrl,
        "failureCallbackUrl": params.failureCallbackUrl,
      },
      contentType: "application/json",
      bodyEncoding: "json",
      requestOptions: requestOptions,
    );
    final parsed = Planet.fromJson(
      response.body is Map<String, Object?>
          ? response.body
          : Map<String, Object?>.from(response.body as Map? ?? const {}),
    );
    return RawResponse(
      statusCode: response.statusCode,
      headers: response.headers,
      rawBody: response.rawBody,
      body: parsed,
    );
  }

  Future<RawResponse<Planet>> retrieve(
    PlanetsRetrieveParams params, {
    RequestOptions? requestOptions,
  }) async {
    final response = await _client.requestRaw(
      "GET",
      "/planets/{planetId}",
      pathParams: {"planetId": params.planetId},
      queryParams: const {},
      headers: const {},
      cookies: const {},
      requestOptions: requestOptions,
    );
    final parsed = Planet.fromJson(
      response.body is Map<String, Object?>
          ? response.body
          : Map<String, Object?>.from(response.body as Map? ?? const {}),
    );
    return RawResponse(
      statusCode: response.statusCode,
      headers: response.headers,
      rawBody: response.rawBody,
      body: parsed,
    );
  }

  Future<RawResponse<Planet>> update(
    PlanetsUpdateParams params, {
    RequestOptions? requestOptions,
  }) async {
    final response = await _client.requestRaw(
      "PUT",
      "/planets/{planetId}",
      pathParams: {"planetId": params.planetId},
      queryParams: const {},
      headers: const {},
      cookies: const {},
      body: {
        "name": params.name,
        "description": params.description,
        "type": params.type,
        "habitabilityIndex": params.habitabilityIndex,
        "physicalProperties": params.physicalProperties,
        "atmosphere": params.atmosphere,
        "discoveredAt": params.discoveredAt,
        "image": params.image,
        "satellites": params.satellites,
        "creator": params.creator,
        "tags": params.tags,
        "successCallbackUrl": params.successCallbackUrl,
        "failureCallbackUrl": params.failureCallbackUrl,
      },
      contentType: "application/json",
      bodyEncoding: "json",
      requestOptions: requestOptions,
    );
    final parsed = Planet.fromJson(
      response.body is Map<String, Object?>
          ? response.body
          : Map<String, Object?>.from(response.body as Map? ?? const {}),
    );
    return RawResponse(
      statusCode: response.statusCode,
      headers: response.headers,
      rawBody: response.rawBody,
      body: parsed,
    );
  }

  Future<RawResponse<void>> delete(
    PlanetsDeleteParams params, {
    RequestOptions? requestOptions,
  }) async {
    final response = await _client.requestRaw(
      "DELETE",
      "/planets/{planetId}",
      pathParams: {"planetId": params.planetId},
      queryParams: const {},
      headers: const {},
      cookies: const {},
      requestOptions: requestOptions,
    );
    final parsed = null;
    return RawResponse(
      statusCode: response.statusCode,
      headers: response.headers,
      rawBody: response.rawBody,
      body: parsed,
    );
  }

  Future<RawResponse<Map<String, Object?>>> uploadImage(
    PlanetsUploadImageParams params, {
    RequestOptions? requestOptions,
  }) async {
    final response = await _client.requestRaw(
      "POST",
      "/planets/{planetId}/image",
      pathParams: {"planetId": params.planetId},
      queryParams: const {},
      headers: const {},
      cookies: const {},
      body: {"image": params.image},
      contentType: "multipart/form-data",
      bodyEncoding: "multipart",
      requestOptions: requestOptions,
    );
    final parsed = response.body is Map<String, Object?>
        ? response.body
        : Map<String, Object?>.from(response.body as Map? ?? const {});
    return RawResponse(
      statusCode: response.statusCode,
      headers: response.headers,
      rawBody: response.rawBody,
      body: parsed,
    );
  }
}

class CelestialBodiesResource {
  final ApiClient _client;
  late final CelestialBodiesResourceRawResponses withRawResponse;

  CelestialBodiesResource(this._client) {
    withRawResponse = CelestialBodiesResourceRawResponses(_client);
  }

  Future<CelestialBody> create(
    CelestialBodiesCreateParams params, {
    RequestOptions? requestOptions,
  }) async {
    final response = await _client.request(
      "POST",
      "/celestial-bodies",
      pathParams: const {},
      queryParams: const {},
      headers: const {},
      cookies: const {},
      body: params.body,
      contentType: "application/json",
      bodyEncoding: "json",
      requestOptions: requestOptions,
    );
    return CelestialBody.fromJson(
      response is Map<String, Object?>
          ? response
          : Map<String, Object?>.from(response as Map? ?? const {}),
    );
  }
}

class CelestialBodiesCreateParams {
  final CelestialBody body;

  const CelestialBodiesCreateParams({required this.body});

  Map<String, Object?> toJson() => {if (body != null) "body": body};
}

class CelestialBodiesResourceRawResponses {
  final ApiClient _client;
  const CelestialBodiesResourceRawResponses(this._client);

  Future<RawResponse<CelestialBody>> create(
    CelestialBodiesCreateParams params, {
    RequestOptions? requestOptions,
  }) async {
    final response = await _client.requestRaw(
      "POST",
      "/celestial-bodies",
      pathParams: const {},
      queryParams: const {},
      headers: const {},
      cookies: const {},
      body: params.body,
      contentType: "application/json",
      bodyEncoding: "json",
      requestOptions: requestOptions,
    );
    final parsed = CelestialBody.fromJson(
      response.body is Map<String, Object?>
          ? response.body
          : Map<String, Object?>.from(response.body as Map? ?? const {}),
    );
    return RawResponse(
      statusCode: response.statusCode,
      headers: response.headers,
      rawBody: response.rawBody,
      body: parsed,
    );
  }
}

class AuthenticationResource {
  final ApiClient _client;
  late final AuthenticationResourceRawResponses withRawResponse;

  AuthenticationResource(this._client) {
    withRawResponse = AuthenticationResourceRawResponses(_client);
  }

  Future<User> createUser({
    AuthenticationCreateUserParams params =
        const AuthenticationCreateUserParams(),
    RequestOptions? requestOptions,
  }) async {
    final response = await _client.request(
      "POST",
      "/user/signup",
      pathParams: const {},
      queryParams: const {},
      headers: const {},
      cookies: const {},
      body: {
        "name": params.name,
        "email": params.email,
        "password": params.password,
      },
      contentType: "application/json",
      bodyEncoding: "json",
      requestOptions: requestOptions,
    );
    return User.fromJson(
      response is Map<String, Object?>
          ? response
          : Map<String, Object?>.from(response as Map? ?? const {}),
    );
  }

  Future<Token> createToken({
    AuthenticationCreateTokenParams params =
        const AuthenticationCreateTokenParams(),
    RequestOptions? requestOptions,
  }) async {
    final response = await _client.request(
      "POST",
      "/auth/token",
      pathParams: const {},
      queryParams: const {},
      headers: const {},
      cookies: const {},
      body: {"email": params.email, "password": params.password},
      contentType: "application/json",
      bodyEncoding: "json",
      requestOptions: requestOptions,
    );
    return Token.fromJson(
      response is Map<String, Object?>
          ? response
          : Map<String, Object?>.from(response as Map? ?? const {}),
    );
  }

  Future<User> listMe({RequestOptions? requestOptions}) async {
    final response = await _client.request(
      "GET",
      "/me",
      pathParams: const {},
      queryParams: const {},
      headers: const {},
      cookies: const {},
      requestOptions: requestOptions,
    );
    return User.fromJson(
      response is Map<String, Object?>
          ? response
          : Map<String, Object?>.from(response as Map? ?? const {}),
    );
  }
}

class AuthenticationCreateUserParams {
  final String? name;
  final String? email;
  final String? password;

  const AuthenticationCreateUserParams({this.name, this.email, this.password});

  Map<String, Object?> toJson() => {
    if (name != null) "name": name,
    if (email != null) "email": email,
    if (password != null) "password": password,
  };
}

class AuthenticationCreateTokenParams {
  final String? email;
  final String? password;

  const AuthenticationCreateTokenParams({this.email, this.password});

  Map<String, Object?> toJson() => {
    if (email != null) "email": email,
    if (password != null) "password": password,
  };
}

class AuthenticationResourceRawResponses {
  final ApiClient _client;
  const AuthenticationResourceRawResponses(this._client);

  Future<RawResponse<User>> createUser({
    AuthenticationCreateUserParams params =
        const AuthenticationCreateUserParams(),
    RequestOptions? requestOptions,
  }) async {
    final response = await _client.requestRaw(
      "POST",
      "/user/signup",
      pathParams: const {},
      queryParams: const {},
      headers: const {},
      cookies: const {},
      body: {
        "name": params.name,
        "email": params.email,
        "password": params.password,
      },
      contentType: "application/json",
      bodyEncoding: "json",
      requestOptions: requestOptions,
    );
    final parsed = User.fromJson(
      response.body is Map<String, Object?>
          ? response.body
          : Map<String, Object?>.from(response.body as Map? ?? const {}),
    );
    return RawResponse(
      statusCode: response.statusCode,
      headers: response.headers,
      rawBody: response.rawBody,
      body: parsed,
    );
  }

  Future<RawResponse<Token>> createToken({
    AuthenticationCreateTokenParams params =
        const AuthenticationCreateTokenParams(),
    RequestOptions? requestOptions,
  }) async {
    final response = await _client.requestRaw(
      "POST",
      "/auth/token",
      pathParams: const {},
      queryParams: const {},
      headers: const {},
      cookies: const {},
      body: {"email": params.email, "password": params.password},
      contentType: "application/json",
      bodyEncoding: "json",
      requestOptions: requestOptions,
    );
    final parsed = Token.fromJson(
      response.body is Map<String, Object?>
          ? response.body
          : Map<String, Object?>.from(response.body as Map? ?? const {}),
    );
    return RawResponse(
      statusCode: response.statusCode,
      headers: response.headers,
      rawBody: response.rawBody,
      body: parsed,
    );
  }

  Future<RawResponse<User>> listMe({RequestOptions? requestOptions}) async {
    final response = await _client.requestRaw(
      "GET",
      "/me",
      pathParams: const {},
      queryParams: const {},
      headers: const {},
      cookies: const {},
      requestOptions: requestOptions,
    );
    final parsed = User.fromJson(
      response.body is Map<String, Object?>
          ? response.body
          : Map<String, Object?>.from(response.body as Map? ?? const {}),
    );
    return RawResponse(
      statusCode: response.statusCode,
      headers: response.headers,
      rawBody: response.rawBody,
      body: parsed,
    );
  }
}
