import 'dart:async';
import 'dart:convert';
import 'dart:io';

// Code generated by Scalar SDK Generator. DO NOT EDIT.

class RequestOptions {
  final Map<String, String> headers;
  final Map<String, Object?> query;
  final Duration? timeout;
  final int? maxRetries;
  final bool rawResponse;

  const RequestOptions({
    this.headers = const {},
    this.query = const {},
    this.timeout,
    this.maxRetries,
    this.rawResponse = false,
  });
}

class RawResponse<T> {
  final int statusCode;
  final Map<String, List<String>> headers;
  final String rawBody;
  final T body;

  const RawResponse({
    required this.statusCode,
    required this.headers,
    required this.rawBody,
    required this.body,
  });
}

class ResultResponse<TData, TError> {
  final TData? data;
  final TError? error;
  final int statusCode;
  final Map<String, List<String>> headers;
  final String rawBody;

  const ResultResponse({
    this.data,
    this.error,
    required this.statusCode,
    required this.headers,
    required this.rawBody,
  });

  bool get isSuccess => data != null;
}

class ApiException implements Exception {
  final String message;
  final int? statusCode;
  final Map<String, List<String>> headers;
  final String? rawBody;
  final String? requestId;
  final Object? body;

  const ApiException(
    this.message, {
    this.statusCode,
    this.headers = const {},
    this.rawBody,
    this.requestId,
    this.body,
  });

  @override
  String toString() => statusCode == null
      ? 'ApiException: $message'
      : 'ApiException($statusCode): $message';
}

class APIConnectionError extends ApiException {
  const APIConnectionError(String message) : super(message);
}

class BadRequestError extends ApiException {
  const BadRequestError(
    String message, {
    Map<String, List<String>> headers = const {},
    String? rawBody,
    String? requestId,
    Object? body,
  }) : super(
         message,
         statusCode: 400,
         headers: headers,
         rawBody: rawBody,
         requestId: requestId,
         body: body,
       );
}

class AuthenticationError extends ApiException {
  const AuthenticationError(
    String message, {
    Map<String, List<String>> headers = const {},
    String? rawBody,
    String? requestId,
    Object? body,
  }) : super(
         message,
         statusCode: 401,
         headers: headers,
         rawBody: rawBody,
         requestId: requestId,
         body: body,
       );
}

class PermissionDeniedError extends ApiException {
  const PermissionDeniedError(
    String message, {
    Map<String, List<String>> headers = const {},
    String? rawBody,
    String? requestId,
    Object? body,
  }) : super(
         message,
         statusCode: 403,
         headers: headers,
         rawBody: rawBody,
         requestId: requestId,
         body: body,
       );
}

class NotFoundError extends ApiException {
  const NotFoundError(
    String message, {
    Map<String, List<String>> headers = const {},
    String? rawBody,
    String? requestId,
    Object? body,
  }) : super(
         message,
         statusCode: 404,
         headers: headers,
         rawBody: rawBody,
         requestId: requestId,
         body: body,
       );
}

class ConflictError extends ApiException {
  const ConflictError(
    String message, {
    Map<String, List<String>> headers = const {},
    String? rawBody,
    String? requestId,
    Object? body,
  }) : super(
         message,
         statusCode: 409,
         headers: headers,
         rawBody: rawBody,
         requestId: requestId,
         body: body,
       );
}

class UnprocessableError extends ApiException {
  const UnprocessableError(
    String message, {
    Map<String, List<String>> headers = const {},
    String? rawBody,
    String? requestId,
    Object? body,
  }) : super(
         message,
         statusCode: 422,
         headers: headers,
         rawBody: rawBody,
         requestId: requestId,
         body: body,
       );
}

class RateLimitError extends ApiException {
  const RateLimitError(
    String message, {
    Map<String, List<String>> headers = const {},
    String? rawBody,
    String? requestId,
    Object? body,
  }) : super(
         message,
         statusCode: 429,
         headers: headers,
         rawBody: rawBody,
         requestId: requestId,
         body: body,
       );
}

class InternalServerError extends ApiException {
  const InternalServerError(
    String message, {
    Map<String, List<String>> headers = const {},
    String? rawBody,
    String? requestId,
    Object? body,
  }) : super(
         message,
         statusCode: 500,
         headers: headers,
         rawBody: rawBody,
         requestId: requestId,
         body: body,
       );
}

class Page<T> {
  final List<T> items;
  final Map<String, Object?> response;
  final String? nextCursor;
  final Future<Page<T>> Function(String nextToken)? fetchNext;

  const Page({
    required this.items,
    required this.response,
    this.nextCursor,
    this.fetchNext,
  });

  bool hasNextPage() => nextCursor != null && fetchNext != null;
  Future<Page<T>> getNextPage() {
    if (!hasNextPage()) throw StateError('No next page is available');
    return fetchNext!(nextCursor!);
  }
}

class StreamEvent<T> {
  final String? event;
  final T data;
  const StreamEvent({this.event, required this.data});
}

class StreamResponse<T> {
  final Stream<StreamEvent<T>> events;
  const StreamResponse(this.events);
  Stream<T> get data => events.map((event) => event.data);
}

class ApiClient {
  final String baseUrl;
  final HttpClient _httpClient;
  final Map<String, String> defaultHeaders;
  final Map<String, String> authHeaders;
  final Map<String, String> authQuery;
  final Map<String, String> authCookies;

  ApiClient({
    String? baseUrl,
    HttpClient? httpClient,
    Map<String, String>? defaultHeaders,
    Map<String, String>? authHeaders,
    Map<String, String>? authQuery,
    Map<String, String>? authCookies,
  }) : baseUrl = (baseUrl ?? "https://galaxy.scalar.com").replaceFirst(
         RegExp(r'/$'),
         '',
       ),
       _httpClient = httpClient ?? HttpClient(),
       defaultHeaders = {'accept': 'application/json', ...?defaultHeaders},
       authHeaders = authHeaders ?? const {},
       authQuery = authQuery ?? const {},
       authCookies = authCookies ?? const {};

  Future<dynamic> request(
    String method,
    String path, {
    Map<String, Object?> pathParams = const {},
    Map<String, Object?> queryParams = const {},
    Map<String, String> headers = const {},
    Map<String, Object?> cookies = const {},
    Object? body,
    String contentType = 'application/json',
    String bodyEncoding = 'json',
    RequestOptions? requestOptions,
  }) async {
    final raw = await requestRaw(
      method,
      path,
      pathParams: pathParams,
      queryParams: queryParams,
      headers: headers,
      cookies: cookies,
      body: body,
      contentType: contentType,
      bodyEncoding: bodyEncoding,
      requestOptions: requestOptions,
    );
    return raw.body;
  }

  Future<RawResponse<dynamic>> requestRaw(
    String method,
    String path, {
    Map<String, Object?> pathParams = const {},
    Map<String, Object?> queryParams = const {},
    Map<String, String> headers = const {},
    Map<String, Object?> cookies = const {},
    Object? body,
    String contentType = 'application/json',
    String bodyEncoding = 'json',
    RequestOptions? requestOptions,
  }) async {
    final resolvedPath = _applyPathParams(path, pathParams);
    final query = _compact({
      ...authQuery,
      ...queryParams,
      ...?requestOptions?.query,
    });
    final uri = Uri.parse(baseUrl + resolvedPath).replace(
      queryParameters: query.map(
        (key, value) => MapEntry(key, value.toString()),
      ),
    );
    final request = await _httpClient
        .openUrl(method.toUpperCase(), uri)
        .timeout(requestOptions?.timeout ?? const Duration(seconds: 30));
    final mergedHeaders = {
      ...defaultHeaders,
      ...authHeaders,
      ...headers,
      ...?requestOptions?.headers,
    };
    for (final entry in mergedHeaders.entries) {
      request.headers.set(entry.key, entry.value);
    }
    final cookieHeader = _cookieHeader({...authCookies, ...cookies});
    if (cookieHeader.isNotEmpty)
      request.headers.set(HttpHeaders.cookieHeader, cookieHeader);
    if (body != null) {
      request.headers.contentType = ContentType.parse(contentType);
      final payload = bodyEncoding == 'binary'
          ? body as List<int>
          : utf8.encode(
              bodyEncoding == 'json' ? jsonEncode(body) : body.toString(),
            );
      request.add(payload);
    }
    final response = await request.close();
    final rawBody = await utf8.decodeStream(response);
    final responseHeaders = <String, List<String>>{};
    response.headers.forEach((name, values) => responseHeaders[name] = values);
    final parsed = _parseBody(rawBody, response.headers.contentType?.mimeType);
    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw _statusError(
        response.statusCode,
        parsed,
        responseHeaders,
        rawBody,
        response.headers.value('x-request-id'),
      );
    }
    return RawResponse(
      statusCode: response.statusCode,
      headers: responseHeaders,
      rawBody: rawBody,
      body: parsed,
    );
  }

  Duration retryDelay(int attempt, Map<String, List<String>> headers) {
    final retryAfterHeader =
        headers['Retry-After']?.first ?? headers['retry-after']?.first;
    final seconds = retryAfterHeader == null
        ? null
        : double.tryParse(retryAfterHeader);
    if (seconds != null && seconds.isFinite && seconds >= 0)
      return Duration(milliseconds: (seconds * 1000).round());
    return Duration(milliseconds: 100 * (1 << attempt.clamp(0, 6)));
  }

  StreamResponse<T> streamRequest<T>(
    String method,
    String path,
    T Function(dynamic value) decode, {
    RequestOptions? requestOptions,
  }) {
    final controller = StreamController<StreamEvent<T>>();
    request(method, path, requestOptions: requestOptions)
        .then((body) {
          controller.add(StreamEvent(data: decode(body)));
          controller.close();
        })
        .catchError(controller.addError);
    return StreamResponse(controller.stream);
  }
}

String _applyPathParams(String path, Map<String, Object?> params) {
  var out = path;
  for (final entry in params.entries) {
    out = out.replaceAll(
      '{${entry.key}}',
      Uri.encodeComponent(entry.value.toString()),
    );
  }
  return out;
}

Map<String, Object?> _compact(Map<String, Object?> values) {
  return Map.fromEntries(values.entries.where((entry) => entry.value != null));
}

String _cookieHeader(Map<String, Object?> values) {
  return _compact(values).entries
      .map(
        (entry) =>
            '${entry.key}=${Uri.encodeComponent(entry.value.toString())}',
      )
      .join('; ');
}

dynamic _parseBody(String rawBody, String? mimeType) {
  if (rawBody.isEmpty) return null;
  if (mimeType == null || mimeType.contains('json')) return jsonDecode(rawBody);
  return rawBody;
}

String _errorMessage(int statusCode, Object? body) {
  if (body is Map && body['message'] != null) return body['message'].toString();
  if (body is Map && body['error'] != null) return body['error'].toString();
  return 'HTTP $statusCode';
}

ApiException _statusError(
  int statusCode,
  Object? body,
  Map<String, List<String>> headers,
  String rawBody,
  String? requestId,
) {
  final message = _errorMessage(statusCode, body);
  switch (statusCode) {
    case 400:
      return BadRequestError(
        message,
        headers: headers,
        rawBody: rawBody,
        requestId: requestId,
        body: body,
      );
    case 401:
      return AuthenticationError(
        message,
        headers: headers,
        rawBody: rawBody,
        requestId: requestId,
        body: body,
      );
    case 403:
      return PermissionDeniedError(
        message,
        headers: headers,
        rawBody: rawBody,
        requestId: requestId,
        body: body,
      );
    case 404:
      return NotFoundError(
        message,
        headers: headers,
        rawBody: rawBody,
        requestId: requestId,
        body: body,
      );
    case 409:
      return ConflictError(
        message,
        headers: headers,
        rawBody: rawBody,
        requestId: requestId,
        body: body,
      );
    case 422:
      return UnprocessableError(
        message,
        headers: headers,
        rawBody: rawBody,
        requestId: requestId,
        body: body,
      );
    case 429:
      return RateLimitError(
        message,
        headers: headers,
        rawBody: rawBody,
        requestId: requestId,
        body: body,
      );
    default:
      if (statusCode >= 500)
        return InternalServerError(
          message,
          headers: headers,
          rawBody: rawBody,
          requestId: requestId,
          body: body,
        );
      return ApiException(
        message,
        statusCode: statusCode,
        headers: headers,
        rawBody: rawBody,
        requestId: requestId,
        body: body,
      );
  }
}
